services:
  picoclaw-deploy:
    image: ghcr.io/lostmaniac/picoclaw-browser:latest
    container_name: picoclaw-deploy
    volumes:
      - ./root:/root
    ports:
      - "2222:22"
    restart: unless-stopped
